### ISSUE TITLE
Review statistics suite

### ISSUE THREAD

**Issue by df79** [archeos/ArcheOS#28]
In Caesar software for statistics are: R (with selected packages), plotdrop and others. R is the best statistic software and we have to keep it in Theodoric (with RStudio: see issue #26). I propose to remove plotdrop and test also PSPP and Scidavis.

**Comment by lucaarcteam** [comment]
Hi,
currently statistics in Theodoric are provided by R and RStudio. I will move this issue to ArcheOS-next. If you have any feedback about statistics package for ArcheOS you can go on in writing them here. I suggest to add new software just in ArcheOS-next in order to keep stabile the alpha of Theodoric. Thank you Denis

**Comment by df79** [comment]
I agree,
Bye

2015-04-07 16:07 GMT+02:00 Luca Bezzi <notifications@github.com>:
